"""Export findings to JSON / CSV / PDF with full provenance and the verdict
reason-trail. Every claim is traceable — no black-box conclusions.
"""

from __future__ import annotations

import csv
import io
import json
from datetime import datetime, timezone
from pathlib import Path

from .config import SETTINGS
from .models import Finding

DISCLAIMER = (
    "Generated by osint-recon for authorized research / educational use only. "
    "Sources are public; verdicts are produced by a deterministic multi-layer "
    "false-positive engine (baseline control-probe + site rule + content "
    "similarity). UNCERTAIN entries are unconfirmed."
)


def _payload(query, findings: list[Finding], summary: dict) -> dict:
    return {
        "tool": "osint-recon",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "query": query.model_dump(exclude_none=True),
        "disclaimer": DISCLAIMER,
        "summary": summary,
        "findings": [f.model_dump() for f in findings],
    }


def to_json(query, findings, summary) -> str:
    return json.dumps(_payload(query, findings, summary), indent=2, default=str)


def to_csv(findings: list[Finding]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["verdict", "confidence", "category", "source", "label", "url", "reasons"])
    for f in findings:
        w.writerow([f.verdict.value, f.confidence, f.category, f.source, f.label,
                    f.url or "", " | ".join(f.reasons)])
    return buf.getvalue()


def to_pdf_html(query, findings, summary) -> str:
    """HTML used for PDF rendering (weasyprint) — also a standalone report."""
    rows = "".join(
        f"<tr class='{f.verdict.value}'><td>{f.verdict.value}</td>"
        f"<td>{f.confidence:.2f}</td><td>{f.source}</td><td>{f.label}</td>"
        f"<td>{'<br>'.join(f.reasons)}</td></tr>"
        for f in findings if f.is_hit
    )
    return f"""<html><head><meta charset='utf-8'><style>
    body{{font:12px sans-serif}} table{{border-collapse:collapse;width:100%}}
    td,th{{border:1px solid #ccc;padding:4px;text-align:left;vertical-align:top}}
    .FOUND{{background:#eafaef}} .UNCERTAIN{{background:#fdf6e3}}
    </style></head><body>
    <h1>osint-recon report</h1>
    <p><b>Query:</b> {json.dumps(query.model_dump(exclude_none=True))}</p>
    <p><small>{DISCLAIMER}</small></p>
    <h2>Hits</h2>
    <table><tr><th>Verdict</th><th>Conf</th><th>Source</th><th>Label</th><th>Reasons</th></tr>
    {rows}</table>
    <h2>Summary</h2><pre>{json.dumps(summary, indent=2)}</pre>
    </body></html>"""


def save(query, findings, summary, fmt: str, out: str | None = None) -> Path:
    reports = Path(SETTINGS.reports_dir)
    reports.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    path = Path(out) if out else reports / f"recon-{stamp}.{fmt}"

    if fmt == "json":
        path.write_text(to_json(query, findings, summary), encoding="utf-8")
    elif fmt == "csv":
        path.write_text(to_csv(findings), encoding="utf-8")
    elif fmt == "pdf":
        html = to_pdf_html(query, findings, summary)
        try:
            from weasyprint import HTML  # optional dependency

            HTML(string=html).write_pdf(str(path))
        except Exception:
            path = path.with_suffix(".html")
            path.write_text(html, encoding="utf-8")
    else:
        raise ValueError(f"unknown format: {fmt}")
    return path
