"""Export findings to JSON / CSV / PDF with full provenance and the verdict
reason-trail. Every claim is traceable — no black-box conclusions.
"""

from __future__ import annotations

import csv
import io
import json
from datetime import datetime, timezone
from pathlib import Path

from .config import SETTINGS
from .models import Finding

DISCLAIMER = (
    "Generated by osint-recon for authorized research / educational use only. "
    "Sources are public; verdicts are produced by a deterministic multi-layer "
    "false-positive engine (baseline control-probe + site rule + content "
    "similarity). UNCERTAIN entries are unconfirmed."
)


def _payload(query, findings: list[Finding], summary: dict) -> dict:
    return {
        "tool": "osint-recon",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "query": query.model_dump(exclude_none=True),
        "disclaimer": DISCLAIMER,
        "summary": summary,
        "findings": [f.model_dump() for f in findings],
    }


def to_json(query, findings, summary) -> str:
    return json.dumps(_payload(query, findings, summary), indent=2, default=str)


def to_csv(findings: list[Finding]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["verdict", "confidence", "category", "source", "label", "url", "reasons"])
    for f in findings:
        w.writerow([f.verdict.value, f.confidence, f.category, f.source, f.label,
                    f.url or "", " | ".join(f.reasons)])
    return buf.getvalue()


def to_pdf_html(query, findings, summary) -> str:
    """HTML used for PDF rendering (weasyprint) — also a standalone report."""
    rows = "".join(
        f"<tr class='{f.verdict.value}'><td>{f.verdict.value}</td>"
        f"<td>{f.confidence:.2f}</td><td>{f.source}</td><td>{f.label}</td>"
        f"<td>{'<br>'.join(f.reasons)}</td></tr>"
        for f in findings if f.is_hit
    )
    return f"""<html><head><meta charset='utf-8'><style>
    body{{font:12px sans-serif}} table{{border-collapse:collapse;width:100%}}
    td,th{{border:1px solid #ccc;padding:4px;text-align:left;vertical-align:top}}
    .FOUND{{background:#eafaef}} .UNCERTAIN{{background:#fdf6e3}}
    </style></head><body>
    <h1>osint-recon report</h1>
    <p><b>Query:</b> {json.dumps(query.model_dump(exclude_none=True))}</p>
    <p><small>{DISCLAIMER}</small></p>
    <h2>Hits</h2>
    <table><tr><th>Verdict</th><th>Conf</th><th>Source</th><th>Label</th><th>Reasons</th></tr>
    {rows}</table>
    <h2>Summary</h2><pre>{json.dumps(summary, indent=2)}</pre>
    </body></html>"""


def entity_report(run_id: int) -> dict:
    """Entity-centric report for a stored run: identities, their corroborating
    observations (with provenance), and changes since the prior run."""
    from .store import get_db, repo
    from .store import models_db as m

    db = get_db()
    with db.session() as s:
        run = s.get(m.Run, run_id)
        if not run:
            raise ValueError(f"no such run: {run_id}")
        target = s.get(m.Target, run.target_id)
        entities = repo.list_entities(s, run.target_id)
        changes = repo.list_changes(s, target_id=run.target_id)
        return {
            "tool": "osint-recon",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "run_id": run_id,
            "target": {"id": target.id, "label": target.label, "query": target.query},
            "disclaimer": DISCLAIMER,
            "identities": [
                {
                    "id": e.id, "label": e.label, "confidence": e.confidence,
                    "flags": e.flags, "attributes": e.attributes,
                    "evidence": [
                        {"source": o.source, "label": o.label, "url": o.url,
                         "verdict": o.verdict, "confidence": o.confidence,
                         "reliability": o.reliability, "reasons": o.reasons}
                        for o in e.observations if o.verdict in ("FOUND", "UNCERTAIN")
                    ],
                }
                for e in entities
            ],
            "changes": [
                {"kind": c.kind, "source": c.source, "label": c.label,
                 "detail": c.detail, "at": c.created_at.isoformat()}
                for c in changes
            ],
        }


def save(query, findings, summary, fmt: str, out: str | None = None) -> Path:
    reports = Path(SETTINGS.reports_dir)
    reports.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    path = Path(out) if out else reports / f"recon-{stamp}.{fmt}"

    if fmt == "json":
        path.write_text(to_json(query, findings, summary), encoding="utf-8")
    elif fmt == "csv":
        path.write_text(to_csv(findings), encoding="utf-8")
    elif fmt == "pdf":
        html = to_pdf_html(query, findings, summary)
        try:
            from weasyprint import HTML  # optional dependency

            HTML(string=html).write_pdf(str(path))
        except Exception:
            path = path.with_suffix(".html")
            path.write_text(html, encoding="utf-8")
    else:
        raise ValueError(f"unknown format: {fmt}")
    return path
